---
node_exporter_binary_local_dir: "/usr/local/bin"
node_exporter_web_listen_address: "0.0.0.0:9100"
node_exporter_web_telemetry_path: "/metrics"

_node_exporter_system_group: "node-exporter"
_node_exporter_system_user: "{{ _node_exporter_system_group }}"