---
- name: Update lab machines
  hosts: labmachines
  remote_user: mzr

  tasks:
  - name: Add the user 'test1' with a specific uid and a primary group of 'student'
    ansible.builtin.user:
      name: test1
      comment: test account
      uid: 1040
      group: student

  - name: Remove the user 'test2' with a specific uid and a primary group of 'student'
    ansible.builtin.user:
      name: test2
      comment: test account to remove
      uid: 1041
      group: student
      state: absent
      remove: yes
