---
- hosts: labmachines

  tasks:
    - name: Create the node_exporter group
      group:
        name: node_exporter
        state: present
        system: true

    - name: Create the node_exporter user
      user:
        name: node_exporter
        groups: node_exporter
        append: true
        shell: /usr/sbin/nologin
        system: true
        create_home: false
        home: /

    - block:
        - name: Get latest release
          uri:
            url: "https://api.github.com/repos/prometheus/node_exporter/releases/latest"
            method: GET
            return_content: true
            status_code: 200
            body_format: json
            user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
            password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
          no_log: true
          register: _latest_release
          until: _latest_release.status == 200
          retries: 5

        - name: "Set node_exporter version to {{ _latest_release.json.tag_name[1:] }}"
          set_fact:
            node_exporter_version: "{{ _latest_release.json.tag_name[1:] }}"

        - name: Get checksum list from github
          set_fact:
            _checksums: "{{ lookup('url', 'https://github.com/prometheus/node_exporter/releases/download/v' + node_exporter_version + '/sha256sums.txt', wantlist=True) | list }}"
            run_once: true

        - name: "Get checksum for {{ go_arch }} architecture"
          set_fact:
            node_exporter_checksum: "{{ item.split(' ')[0] }}"
          with_items: "{{ _checksums }}"
          when:
            - "('linux-' + go_arch + '.tar.gz') in item"
      delegate_to: localhost
      run_once: true

    - name: Check if node_exporter is installed
      stat:
        path: "/usr/local/bin/node_exporter"
      register: __node_exporter_is_installed
      check_mode: false

    - name: Try install node_exporter if not installed
      block:
      - name: Download node_exporter binary to local folder
        become: false
        get_url:
          url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
          dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
          mode: '0644'
        register: _download_binary
        until: _download_binary is succeeded
        retries: 5
        delay: 2
        delegate_to: localhost
        check_mode: false
        
      - name: Unpack node_exporter binary
        become: false
        unarchive:
          dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
          tmp: "/tmp"
          creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}/node_exporter"
        delegate_to: localhost
        check_mode: false

      - name: Propagate node_exporter binaries
        copy:
          src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}/node_exporter"
          dest: "/usr/local/bin/node_exporter"
          mode: 0755
          owner: root
          group: root
        notify: restart node_exporter
        when: not ansible_check_mode
      when: not __node_exporter_is_installed.stat.exists

    - name: Copy node_exporter systemd service file
      template:
        src: node_exporter.service.js
        dest: /etc/systemd/system/node_exporter.service
        owner: root
        group: root
        mode: 0644
      notify: restart node_exporter

    - name: Ensure node_exporter is enabled on boot
      become: true
      systemd:
        daemon_reload: true
        name: node_exporter
        enabled: true
        state: started
      when:
        - not ansible_check_mode